<a href="https://colab.research.google.com/github/DucBox/Python_Train/blob/main/Day_12_(Initialize_Numpy_Tensorflow_Pytorch).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import torch

# np.zeros(shape)
# torch.zeros(shape)
# tf.zeros(shape)

In [4]:
np_array_zero = np.zeros((2, 3))
print(np_array_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
torch_array_zero = torch.zeros((2, 3))
print(torch_array_zero)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
tf_array_zero = tf.zeros((2, 3))
print(tf_array_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# np.ones(shape)
# torch.ones(shape)
# tf.ones(shape)

In [11]:
np_array_ones = np.ones((2, 3))
print(np_array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
torch_array_ones = torch.ones((2, 3))
print(torch_array_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
tf_array_ones = tf.ones((2, 3))
print(tf_array_ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


# np.full(shape, value)
# torch.full(shape, value)
# tf.fill(shape, value)

In [14]:
np_full = np.full((2, 3), 5)
print(np_full)

[[5 5 5]
 [5 5 5]]


In [15]:
torch_full = torch.full((2, 3), 5)
print(torch_full)

tensor([[5, 5, 5],
        [5, 5, 5]])


In [16]:
tf_full = tf.fill((2, 3), 5)
print(tf_full)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)
